dist: trusty

jdk:
  - openjdk8

script:
  - mvn clean package

after_success:
  - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 245523304691.dkr.ecr.us-east-2.amazonaws.com
  - docker build -t dataparser .
  - docker tag dataanalyzer:latest 245523304691.dkr.ecr.us-east-2.amazonaws.com/dataanalyzer:latest
  - docker push 245523304691.dkr.ecr.us-east-2.amazonaws.com/dataanalyzer:latest
