dist: trusty

jdk:
  - openjdk11

script:
  - git fetch --unshallow
  - mvn clean pac

after_success:
  - docker build -t speech4j/tenant-service .gt
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push speech4j/tenant-service
