dist: trusty

jdk:
  - openjdk8

script:
  - mvn clean package

after_success:
  - docker build -t dataparser .
  - docker tag dataanalyzer:latest 245523304691.dkr.ecr.us-east-2.amazonaws.com/dataanalyzer:latest
  - docker push 245523304691.dkr.ecr.us-east-2.amazonaws.com/dataanalyzer:latest
